implemented the hero
DevBigEazi/JaraFi_Landing_Page pull request #14
Opened 2024-09-18 09:37 UTC by hola-official

@DevBigEazi #6  #muha/hero

2024-09-18 11:17 UTC, DevBigEazi requested changes

2024-09-18 11:17 UTC, DevBigEazi commented on src/sections/Hero.jsx
<img width="728" alt="review-1" src="https://github.com/user-attachments/assets/a93b3295-0e31-4f4b-9dfa-b9675dd32708">

The padding are too much. Stick with the designs

2024-09-18 11:17 UTC, DevBigEazi commented on src/sections/Hero.jsx
<img width="523" alt="review-2" src="https://github.com/user-attachments/assets/128489cd-e529-4320-a5ea-6539c322a22a">

change the flex direction from 678px screen downward.

2024-09-18 11:19 UTC, DevBigEazi commented
Make sure the form is submiiting data to google sheet

2024-09-19 09:02 UTC, hola-official commented on src/sections/Hero.jsx
> +          <button className="self-start mt-2 sm:mt-4 h-11 max-sm:w-full text-center border border-primary transition-all duration-500 hover:bg-whitesmoke rounded-lg text-primary text-base max-sm:text
done sir

2024-09-19 09:02 UTC, hola-official commented on src/sections/Hero.jsx
> +            Join Our Community
resolved sir

2024-09-19 09:03 UTC, hola-official commented on src/sections/Hero.jsx
done sir

2024-09-19 09:04 UTC, hola-official commented
@DevBigEazi all the issue have being resolved sir

2024-09-19 11:11 UTC, DevBigEazi requested changes
Remove the codes you commented out

2024-09-19 11:11 UTC, DevBigEazi commented on src/components/Modal.jsx
> +        className={`fixed inset-0 bg-[#0f0140] z-50 flex items-center max-w-[978px] max-sm:mt-14 sm:h-[493px] m-auto justify-center p-4 transition-transform duration-400 ${
leverage the color configuration in tailwind.config.js

2024-09-19 11:11 UTC, DevBigEazi commented on src/components/Modal.jsx
> +        <div className="relative w-full max-w-md bg-[#0f0140] rounded-lg shadow-lg">
leverage the color configuration in tailwind.config.js

2024-09-19 11:11 UTC, DevBigEazi commented on src/components/Modal.jsx
> +                  className="w-full p-3 bg-[#1D143E] border border-[#FFFFFF80] rounded-lg text-white placeholder-gray-400"
leverage the color configuration in tailwind.config.js

2024-09-19 11:11 UTC, DevBigEazi commented on src/components/Modal.jsx
> +                className="w-full bg-[#F9F6F3] text-[#0F0140] py-3 rounded-lg font-normal hover:bg-gray-100 transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
leverage the color configuration in tailwind.config.js

2024-09-19 11:11 UTC, DevBigEazi commented on src/components/Modal.jsx
> +
Add a comment to specify what this useEffect does....

2024-09-19 11:11 UTC, DevBigEazi commented on src/sections/Hero.jsx
> +  };
add a sapce before the next function

2024-09-19 11:11 UTC, DevBigEazi commented on src/sections/Hero.jsx
> +  useEffect(() => {
Add a comment to specify what this useEffect does

2024-09-19 11:28 UTC, DevBigEazi commented
<img width="265" alt="review-3" src="https://github.com/user-attachments/assets/2097042a-ac2f-4f70-98ff-f62ca51637d0">

let the section paddingLeft be the same as the navbar

2024-09-19 11:33 UTC, hola-official commented on src/components/Modal.jsx
> +        className={`fixed inset-0 bg-[#0f0140] z-50 flex items-center max-w-[978px] max-sm:mt-14 sm:h-[493px] m-auto justify-center p-4 transition-transform duration-400 ${
done

2024-09-19 11:39 UTC, hola-official commented
> <img alt="review-3" width="265" src="https://private-user-images.githubusercontent.com/102731426/368968552-2097042a-ac2f-4f70-98ff-f62ca51637d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDU4ODQsIm5iZiI6MTcyNjc0NTU4NCwicGF0aCI6Ii8xMDI3MzE0MjYvMzY4OTY4NTUyLTIwOTcwNDJhLWFjMmYtNGY3MC05OGZmLWY2MmNhNTE2MzdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxMTMzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGFjYWRjODlhZGRjNmRjNTMyMWFmYjVmZTUxY2QyZGVmM2NkMzc2NmI4NDgwYmUzYzZlYWZmNjFjMjYxMmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wsLPNmLgfHNgb1ddEVwalXuEr7e-kR5VN7dTz1jStRc">
> let the section paddingLeft be the same as the navbar

done sir

2024-09-19 12:10 UTC, hola-official commented on src/components/Modal.jsx
> +                className="w-full bg-[#F9F6F3] text-[#0F0140] py-3 rounded-lg font-normal hover:bg-gray-100 transition duration-300 disabled:opacity-50 disabled:cursor-not-allowed"
have fix it sir

2024-09-19 13:52 UTC, DevBigEazi commented
kindly resolve the conflict @hola-official

2024-09-19 14:22 UTC, DevBigEazi commented
<img width="481" alt="review-4" src="https://github.com/user-attachments/assets/333edd54-790a-4252-ae21-db2cc89d01f4">
<img width="493" alt="review-5" src="https://github.com/user-attachments/assets/db17afd3-334c-480c-9956-f88ecf5bda81">
Reduce the spaces in between 1024px screen and 768px screen

2024-09-19 18:21 UTC, hola-official commented
@DevBigEazi conflicts resolved sir

2024-09-19 20:13 UTC, merged